// Preliminary Physics — Section II short-answer sub-questions
// Sourced from the 2021 NSW Independent Trial Exams, Physics Year 11 Examination,
// with official marking criteria and sample answers from that paper's marking
// guidelines. Drawing-only or graph-drawing sub-parts (17a, 17b, 18, 24) were
// dropped, matching the approach used for the Preliminary Biology quiz's own
// text-only exam bank.
const SA_QUESTIONS = [
  {
    "id": "JR20-Q19(a)",
    "year": 2020,
    "n": 19,
    "part": "a",
    "marks": 2,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "JR20_q19a.png",
    "w": 1205,
    "h": 316,
    "criteria": "Outlines the difference between magnetised and unmagnetised materials — 2\nProvides one correct point — 1",
    "sample": "In an unmagnetised material, the magnetic fields produced by the individual domains point in random directions, so their overall effect cancels out and the net magnetic field is zero. In a magnetised material, the domains are aligned (e.g. by an external field), so the sum of their individual effects is non-zero and the material has a net magnetic field."
  },
  {
    "id": "JR20-Q20",
    "year": 2020,
    "n": 20,
    "part": null,
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "JR20_q20.png",
    "w": 1205,
    "h": 483,
    "criteria": "Draws a correct free-body diagram, correctly resolves the forces, and correctly calculates T — 3\nAny two of the above, or makes one calculation error — 2\nShows relevant working — 1",
    "sample": "By symmetry, both strings make an angle of 30 degrees with the horizontal (60 degrees with the wall). Resolving vertically: 2T sin30 = mg, so T = mg / (2 sin30) = (1.5 x 9.8) / (2 x 0.5) = 14.7 N."
  },
  {
    "id": "JR20-Q21",
    "year": 2020,
    "n": 21,
    "part": null,
    "marks": 2,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "JR20_q21.png",
    "w": 1205,
    "h": 427,
    "criteria": "Provides correct justification for conservation of kinetic energy and not momentum (for the ball alone), identifying that considering the ball-and-Earth system conserves momentum too — 2\nProvides correct justification for conservation of kinetic energy only, or states momentum is not conserved without further justification — 1",
    "sample": "Since the ball returns to the same height, its kinetic energy just before hitting the ground equals its kinetic energy just after — kinetic energy is conserved. However, the ball's velocity reverses direction, so its momentum has changed — momentum of the ball alone is not conserved. If instead we consider the system of the ball and the Earth together, momentum of that whole system is conserved, since the change in the ball's momentum is matched by an equal and opposite change in the Earth's momentum, with no net external force acting on the system."
  },
  {
    "id": "JR20-Q22",
    "year": 2020,
    "n": 22,
    "part": null,
    "marks": 2,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "JR20_q22.png",
    "w": 1205,
    "h": 520,
    "criteria": "Correctly explains the cause and effect: electron migration due to the rod, grounding, and the resulting positive charge — 2\nProvides one of the above correctly — 1",
    "sample": "As the negatively charged rod is brought near the sphere, it repels the sphere's free electrons to the far side, leaving the near side positively charged (induction) while the sphere as a whole is still neutral. If the sphere is then earthed while the rod remains nearby, the repelled electrons flow away to earth. When the earth connection and then the rod are removed, the sphere is left with an overall positive charge."
  },
  {
    "id": "JR20-Q23",
    "year": 2020,
    "n": 23,
    "part": null,
    "marks": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "JR20_q23.png",
    "w": 1205,
    "h": 483,
    "criteria": "Correctly finds the Doppler-shifted frequency, substitutes into the correct formula, and correctly obtains the speed of the train — 3\nAny two of the above — 2\nAny one of the above — 1",
    "sample": "The beat frequency means the approaching train's whistle is heard at f' = 424 + 3 = 427 Hz (since an approaching source causes an increase in the heard frequency).\nUsing the Doppler formula f' = f (v / (v - v_source)) with v = 340 m/s:\n427 = 424 x (340 / (340 - v_train))\n340 - v_train = 340 x (424/427)\nv_train = 340 - 340 x (424/427) = 2.39 m/s (about 8.6 km/h)."
  },
  {
    "id": "JR20-Q24(a)",
    "year": 2020,
    "n": 24,
    "part": "a",
    "marks": 3,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "JR20_q24.png",
    "w": 1205,
    "h": 335,
    "criteria": "Correctly determines the reaction distance and braking distance, and draws the appropriate conclusion — 3\nCorrectly determines the reaction distance OR braking distance, and draws the appropriate conclusion — 2\nProvides some relevant conclusion — 1",
    "sample": "Initial speed = 90 km/h = 25 m/s.\nReaction distance = v x t = 25 x 0.75 = 18.75 m.\nBraking distance: v^2 = u^2 + 2as, with v=0, u=25, a=-10: 0 = 625 - 20s, so s = 31.25 m.\nTotal stopping distance = 18.75 + 31.25 = 50 m, which is greater than the 40 m available — so yes, the car hits the barrier."
  },
  {
    "id": "JR20-Q24(b)",
    "year": 2020,
    "n": 24,
    "part": "b",
    "marks": 3,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "JR20_q24.png",
    "w": 1205,
    "h": 335,
    "criteria": "Correctly obtains expressions for the reaction and braking distances and computes the maximum speed — 3\nCorrectly obtains an expression for reaction OR braking distance and computes the maximum speed — 2\nProvides some relevant information — 1",
    "sample": "Reaction distance = 0.75u. Braking distance (from v^2 = u^2 + 2as, v=0, a=-10): s = u^2/20.\nTotal distance = 0.75u + u^2/20 = 40, so u^2 + 15u - 800 = 0.\nUsing the quadratic formula: u = (-15 + sqrt(15^2 + 4x800)) / 2 = 21.8 m/s (about 78.3 km/h)."
  },
  {
    "id": "JR20-Q25",
    "year": 2020,
    "n": 25,
    "part": null,
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "JR20_q25.png",
    "w": 1205,
    "h": 1075,
    "criteria": "Correctly identifies the applied force at which acceleration is zero and uses it to calculate the coefficient of kinetic friction — 3\nIdentifies the applied force at zero acceleration but makes a calculation error, or uses an equivalent valid method with a minor error — 2\nShows relevant working — 1",
    "sample": "Extrapolating the straight-line part of the graph back to where acceleration = 0 gives an applied force of about 50 N — this is the point where the applied force exactly balances the kinetic friction force, so f_k = 50 N.\nSince f_k = mu_k x N = mu_k x mg: mu_k = f_k / (mg) = 50 / (100 x 9.8) = 0.05."
  },
  {
    "id": "P22-Q16",
    "year": 2022,
    "n": 16,
    "part": null,
    "marks": 3,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "P22_q16.png",
    "w": 1644,
    "h": 1240,
    "criteria": "Correctly determines the magnitude of the displacement using the scale diagram — 2\nCorrectly determines the direction (bearing) of the displacement — 1",
    "sample": "Measuring the straight-line distance from X to Y on the scale diagram (where 10 m is shown as a fixed length) and the angle from north gives a displacement of approximately 50 m, on a bearing of roughly 117 degrees."
  },
  {
    "id": "P22-Q17",
    "year": 2022,
    "n": 17,
    "part": null,
    "marks": 3,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "P22_q17.svg",
    "w": 900,
    "h": 294,
    "criteria": "Draws a correct vector diagram for Vx - Vy and determines the correct magnitude and bearing — 3\nDraws a correct vector diagram and determines only the magnitude, or makes a minor direction error — 2\nProvides some correct relevant working (e.g. correctly identifies Vx and -Vy) — 1",
    "sample": "Relative velocity of X with respect to Y = Vx - Vy = Vx + (-Vy).\nVx = 150 kph bearing 180 (i.e. 150 kph south). -Vy = 250 kph bearing 270 (reversing 250 kph bearing 090).\nAdding these as vectors (south and west components) gives a resultant of magnitude sqrt(150^2 + 250^2) = 291.5 kph, on a bearing of 180 + arctan(250/150) = about 239 degrees."
  },
  {
    "id": "P22-Q19(a)",
    "year": 2022,
    "n": 19,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_q19a.svg",
    "w": 900,
    "h": 294,
    "criteria": "Completes Newton's First Law — 1",
    "sample": "...rest until acted on by an unbalanced (net) force."
  },
  {
    "id": "P22-Q19(b)",
    "year": 2022,
    "n": 19,
    "part": "b",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_q19b.svg",
    "w": 900,
    "h": 212,
    "criteria": "Names Newton — 1",
    "sample": "Isaac Newton"
  },
  {
    "id": "P22-Q19(c)",
    "year": 2022,
    "n": 19,
    "part": "c",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_q19c.svg",
    "w": 900,
    "h": 176,
    "criteria": "Provides a correct definition — 1",
    "sample": "Inertia is the property of matter that causes it to resist any change to its state of rest or of uniform motion."
  },
  {
    "id": "P22-Q20(a)",
    "year": 2022,
    "n": 20,
    "part": "a",
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_q20.png",
    "w": 1644,
    "h": 1618,
    "criteria": "Identifies THREE labels correctly — 3\nIdentifies TWO labels correctly — 2\nIdentifies ONE label correctly — 1",
    "sample": "X = normal reaction force, Y = frictional force, Z = weight force (gravity)."
  },
  {
    "id": "P22-Q20(b)",
    "year": 2022,
    "n": 20,
    "part": "b",
    "marks": 2,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_q20.png",
    "w": 1644,
    "h": 1618,
    "criteria": "States the student is correct and identifies the missing force as a force to the right, greater than friction — 2\nIdentifies only that a force to the right is missing — 1",
    "sample": "The student is correct. Since the mass is accelerating to the right, there must be a net force to the right — meaning a driving/applied force to the right, larger than the frictional force Y, is missing from the diagram."
  },
  {
    "id": "P22-Q22",
    "year": 2022,
    "n": 22,
    "part": null,
    "marks": 4,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "P22_q22.png",
    "w": 1644,
    "h": 1290,
    "criteria": "Demonstrates that momentum is conserved and that the collision is inelastic, based on kinetic energy calculations — 4\nCompares momentum and kinetic energy before/after with one error, OR shows momentum is conserved and states that coalescing objects imply an inelastic collision — 3\nCorrectly compares momentum OR kinetic energy before and after — 2\nCompares momentum OR kinetic energy with one error, OR simply states that coalescing objects imply an inelastic collision — 1",
    "sample": "Initial velocity of X = distance/time = 6.0 cm / (3/20 s) = 40 m/s (using the scale and the 20 Hz stroboscope). Final velocity of X and Y combined = 6.0 cm / (4/20 s) = 30 m/s.\nInitial momentum = 0.24 x 40 = 9.6 kg m/s. Final momentum = (0.24 + 0.08) x 30 = 9.6 kg m/s — momentum is conserved.\nKinetic energy before = 0.5 x 0.24 x 40^2 = 192 J. Kinetic energy after = 0.5 x 0.32 x 30^2 = 144 J — kinetic energy is not conserved, so the collision is inelastic."
  },
  {
    "id": "P22-Q24",
    "year": 2022,
    "n": 24,
    "part": null,
    "marks": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P22_q24.png",
    "w": 1644,
    "h": 961,
    "criteria": "Determines the speed of sound using the average time and the correct distance — 3\nDetermines the speed of sound using the average time but an incorrect distance — 2\nDetermines the speed of sound using an incorrect time and an incorrect distance — 1",
    "sample": "Distance from the shouting person to the friend (timer) = 450 m. Distance the echo travels (to the cliff and back to the timer) = 390 + (390 + 450) = 1230 m. Difference in distance = 1230 - 450 = 780 m.\nAverage of the five time differences = (2.37+2.21+2.54+2.31+2.64)/5 = 2.41 s.\nSpeed of sound = 780 / 2.41 = 324 m/s."
  },
  {
    "id": "P22-Q25(a)",
    "year": 2022,
    "n": 25,
    "part": "a",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P22_q25.png",
    "w": 1644,
    "h": 961,
    "criteria": "Describes that sound wave energy transfers from box A to box B, and that this sets up a wave of the same natural frequency as tuning fork A — 2\nDescribes only the transfer of sound wave energy — 1",
    "sample": "Tuning fork A's vibrations make resonance box A vibrate, setting up a sound wave of the same frequency in the air inside it. This sound wave energy travels out of box A, across the gap, and into box B. Because tuning forks A and B are identical (same natural frequency), box B and tuning fork B are set vibrating by the wave — this is resonance."
  },
  {
    "id": "P22-Q25(b)",
    "year": 2022,
    "n": 25,
    "part": "b",
    "marks": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P22_q25.png",
    "w": 1644,
    "h": 961,
    "criteria": "Identifies and justifies TWO improvements to the diagram — 3\nIdentifies and justifies ONE improvement, OR identifies TWO improvements without justification — 2\nIdentifies ONE improvement without justification — 1",
    "sample": "The right-hand resonance box should be drawn the same length as the left-hand box — for resonance to occur reliably, the two boxes (and forks) must be matched, since a closed resonance tube's length depends on the wavelength of the fork's frequency. The spacing of the sound wavefronts drawn between the boxes should also stay constant, since sound travels at a constant speed through air under the same conditions."
  },
  {
    "id": "P22-Q26",
    "year": 2022,
    "n": 26,
    "part": null,
    "marks": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "P22_q26.svg",
    "w": 900,
    "h": 258,
    "criteria": "Identifies the speed of particle movement and the resulting collisions, based on the energy available and the consequent distance between particles — 3\nIdentifies TWO of: particle speed, collisions, energy available, distance between particles — 2\nIdentifies ONE of the above — 1",
    "sample": "When matter is heated, its particles move more energetically and collide more violently with their neighbours, pushing each other further apart as they collide — so the matter expands. When matter is cooled, its particles have less energy, so they collide less violently and use less room to move about — they stay closer together and the matter contracts."
  },
  {
    "id": "P22-Q27",
    "year": 2022,
    "n": 27,
    "part": null,
    "marks": 3,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "P22_q27.svg",
    "w": 900,
    "h": 258,
    "criteria": "Describes the transfer of electrons, resulting in opposite charges that attract — 2-3\nStates only that opposite charges attract — 1",
    "sample": "Rubbing the balloon against the cat's fur transfers electrons between the fur and the balloon, leaving one surface positively charged (having lost electrons) and the other negatively charged (having gained electrons). Since opposite electrostatic charges attract, the cat's hairs are pulled up towards the oppositely-charged balloon."
  },
  {
    "id": "P22-Q28(a)",
    "year": 2022,
    "n": 28,
    "part": "a",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_q28.png",
    "w": 1644,
    "h": 1416,
    "criteria": "Calculates the correct current — 1",
    "sample": "V3 = 18 V, so current in the 3 ohm resistor = 18/3 = 6 A. Since A2 carries the same current as the 3 ohm branch, the reading on A2 = 6 A."
  },
  {
    "id": "P22-Q28(b)",
    "year": 2022,
    "n": 28,
    "part": "b",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_q28.png",
    "w": 1644,
    "h": 1416,
    "criteria": "Calculates the correct voltage — 1",
    "sample": "Voltage V4 = I x R = 9 x 4 = 36 V (using the 9 A reading on A5, which flows through the 4 ohm resistor)."
  },
  {
    "id": "P22-Q28(c)",
    "year": 2022,
    "n": 28,
    "part": "c",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_q28.png",
    "w": 1644,
    "h": 1416,
    "criteria": "Calculates the correct resistance — 1",
    "sample": "R is in parallel with the 3 ohm resistor, so V2 = V3 = 18 V. Current through R = 9 - 6 = 3 A (total current in A1/A5 minus the 6 A through the 3 ohm branch). R = V/I = 18/3 = 6 ohms."
  },
  {
    "id": "P22-Q28(d)",
    "year": 2022,
    "n": 28,
    "part": "d",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_q28.png",
    "w": 1644,
    "h": 1416,
    "criteria": "Calculates the correct voltage — 1",
    "sample": "V1 = V4 + V2 (or V3) = 36 + 18 = 54 V."
  },
  {
    "id": "P22-Q28(e)",
    "year": 2022,
    "n": 28,
    "part": "e",
    "marks": 2,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_q28.png",
    "w": 1644,
    "h": 1416,
    "criteria": "Calculates the correct total resistance using two different methods — 2\nCalculates the correct total resistance using one method — 1",
    "sample": "Method 1: Total R = V1/A1 = 54/9 = 6 ohms.\nMethod 2: The R-ohm and 3 ohm resistors are in parallel with each other, in series with the 4 ohm resistor. 1/parallel R = 1/6 + 1/3, so parallel R = 2 ohms. Total R = 2 + 4 = 6 ohms — the two methods agree."
  },
  {
    "id": "IND21-Q16(a)",
    "year": 2021,
    "n": 16,
    "part": "a",
    "marks": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct answer — 1",
    "sample": "Distance travelled = total area between the graph and the time axis = (6 × 15)/2 + (10 × 25)/2 = 170 m"
  },
  {
    "id": "IND21-Q16(b)",
    "year": 2021,
    "n": 16,
    "part": "b",
    "marks": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct magnitude and direction — 2\nProvides correct magnitude — 1",
    "sample": "Displacement = 45 m south + 125 m north = 80 m north (adding the signed area under the graph before and after it crosses zero)"
  },
  {
    "id": "IND21-Q16(c)",
    "year": 2021,
    "n": 16,
    "part": "c",
    "marks": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct magnitude — 1",
    "sample": "Acceleration = gradient of the graph = 40/16 = 2.5 m/s² north"
  },
  {
    "id": "IND21-Q17(c)",
    "year": 2021,
    "n": 17,
    "part": "c",
    "marks": 2,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "IND21_q17.png",
    "w": 1644,
    "h": 1188,
    "criteria": "Calculates angle — 2\nCalculates acceleration only — 1",
    "sample": "Using s = ut + 1/2 a t^2 with u = 0: a = 2s/t^2 = 2(0.61)/(0.5)^2 = 4.9 m/s^2 (using the t = 0.5 s data point, distance 61 cm = 0.61 m)\nAcceleration down the slope = g sinθ, so 4.9 = 9.8 sinθ, sinθ = 0.5, θ = 30°"
  },
  {
    "id": "IND21-Q19(a)",
    "year": 2021,
    "n": 19,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q19.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates net force — 1",
    "sample": "From F = ma, net force on the box = 12 × 3.0 = 36 N in the direction of motion"
  },
  {
    "id": "IND21-Q19(b)",
    "year": 2021,
    "n": 19,
    "part": "b",
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q19.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates the coefficient of friction correctly — 3\nDetermines the frictional force correctly and calculates the coefficient of friction using the weight force only — 2\nDetermines the frictional force correctly — 1",
    "sample": "Horizontal component of tension in rope = 60 cos 40° = 46 N\nNet force = horizontal component of tension − frictional force, so frictional force = 46 − 36 = 10 N\nVertical component of tension = 60 sin 40° = 39 N\nNormal reaction force N = mg − vertical component of tension = (12 × 9.8) − 39 = 79 N\nKinetic coefficient of friction = friction force / N = 10 / 79 = 0.13"
  },
  {
    "id": "IND21-Q20(a)",
    "year": 2021,
    "n": 20,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Determines acceleration — 1",
    "sample": "At displacement 30 m East, force = 32 N East (read from the graph)\nAcceleration = F/m = 32/5.0 = 6.4 m/s² East"
  },
  {
    "id": "IND21-Q20(b)",
    "year": 2021,
    "n": 20,
    "part": "b",
    "marks": 2,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates work done correctly — 2\nCalculates the area under the graph with an error — 1",
    "sample": "Work done = area under the graph from 0 to 30 m = (25 × 40) + 0.5(40 + 32)(5) = 1000 + 180 = 1180 J"
  },
  {
    "id": "IND21-Q20(c)",
    "year": 2021,
    "n": 20,
    "part": "c",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates velocity — 1",
    "sample": "By the work-energy theorem, kinetic energy gained = work done: 1/2 m v^2 = 1180, so v = sqrt(2 × 1180 / 5.0) = 21.7 m/s East"
  },
  {
    "id": "IND21-Q21",
    "year": 2021,
    "n": 21,
    "part": null,
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q21.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Evaluates BOTH statements about momentum correctly and identifies THREE mistakes about kinetic energy — 3\nEvaluates BOTH statements about momentum correctly and identifies ONE mistake about kinetic energy — 2\nEvaluates BOTH statements about momentum correctly — 1",
    "sample": "Both students are correct to use a vector diagram to compare momentum before and after the explosion, because momentum is a vector and is conserved in all interactions with no external force — the explosion here is an internal force within the system.\nHowever, both are incorrect about kinetic energy: it is a scalar, not a vector, so it cannot be added or compared using a vector diagram. The system's kinetic energy starts at zero and is clearly not zero afterwards, so kinetic energy is not conserved — Carol's conclusion about momentum is right, but Tom's claim that kinetic energy is also conserved is wrong, and neither student's vector-diagram method for energy is valid."
  },
  {
    "id": "IND21-Q22(a)",
    "year": 2021,
    "n": 22,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates magnitude of velocity — 1",
    "sample": "By conservation of momentum: (1000)(20) + 0 = (1000 + 800)v, so v = 20000/1800 = 11.1 m/s to the right"
  },
  {
    "id": "IND21-Q22(b)",
    "year": 2021,
    "n": 22,
    "part": "b",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates impulse — 1",
    "sample": "Momentum of car Y after collision = 800 × 11.1 = 8880 Ns to the right. Since car Y started at rest, its change in momentum (= impulse applied to it by car X) is also 8880 Ns to the right."
  },
  {
    "id": "IND21-Q22(c)",
    "year": 2021,
    "n": 22,
    "part": "c",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates force — 1",
    "sample": "By Newton's Third Law, the impulse on car X is 8880 Ns to the left. Force on car X = impulse / time = 8880 / 0.10 = 88 800 N to the left"
  },
  {
    "id": "IND21-Q23(a)",
    "year": 2021,
    "n": 23,
    "part": "a",
    "marks": 1,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Provides correct answer — 1",
    "sample": "The natural (resonant) frequency of the spring is 70 × 10^3 Hz — the frequency at which the maximum amplitude of vibration (3.5 × 10^-4 cm) occurs in the table."
  },
  {
    "id": "IND21-Q23(b)",
    "year": 2021,
    "n": 23,
    "part": "b",
    "marks": 1,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Identifies ultrasound — 1",
    "sample": "The ultrasonic sound source drives the spring to oscillate."
  },
  {
    "id": "IND21-Q23(c)",
    "year": 2021,
    "n": 23,
    "part": "c",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Identifies increased amplitude and gives the reason — 2\nIdentifies increased amplitude only — 1",
    "sample": "If the intensity of the ultrasound (the driving force) were increased, the amplitude of the spring's oscillations would increase at every frequency, because more energy is being supplied to drive the resonance."
  },
  {
    "id": "IND21-Q25",
    "year": 2021,
    "n": 25,
    "part": null,
    "marks": 7,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "IND21_q25.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Compares in detail the motion of the particles, the energy transfer, and the appearance, with at least ONE example for each type of wave — 6–7\nProvides a comparison of THREE of: motion of particles, energy transfer, appearance, example for each — 4–5\nProvides a comparison of TWO of the above — 2–3\nProvides a comparison of ONE of the above — 1",
    "sample": "In a progressive wave, each particle of the medium undergoes identical vibrations, slightly out of step (out of phase) with its neighbours, and the disturbance itself moves steadily along the medium, transferring energy from one place to another. Its wavelength is the distance between two particles that are in phase, e.g. crest to crest.\nIn a standing wave, energy is not transferred along the medium — it is reflected back and forth between the boundaries of the system. Some points, called nodes, never vibrate at all, while points midway between adjacent nodes, called antinodes, vibrate with maximum amplitude; particles on opposite sides of a node vibrate in opposite phase. Its wavelength is twice the distance between two adjacent nodes.\nBoth transverse and longitudinal waves can be either progressive or standing.\nExamples of progressive waves include surface water waves and sound travelling through open air. Examples of standing waves include a vibrating violin string and the air column inside a wind instrument being played."
  },
  {
    "id": "IND21-Q26(a)",
    "year": 2021,
    "n": 26,
    "part": "a",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "IND21_q26.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the constant temperature and the continued energy input — 2\nIdentifies the constant temperature OR the continued energy input — 1",
    "sample": "While the ice is melting, its temperature stays constant at 0°C even though heat energy is still being supplied at a steady rate. This heat energy is being used to change the ice from the solid state to the liquid state, rather than to raise its temperature — this 'hidden' energy is the latent heat of fusion."
  },
  {
    "id": "IND21-Q26(b)",
    "year": 2021,
    "n": 26,
    "part": "b",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "IND21_q26.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the change in structure of the particles in the solid and liquid states and the need to overcome intermolecular forces — 2\nIdentifies the change in structure OR the need to overcome forces — 1",
    "sample": "The energy supplied is absorbed by the particles of ice and used to overcome the intermolecular forces holding them in fixed positions within the solid lattice. This lets the particles break free of their fixed positions and move over one another, as they do in the liquid state."
  },
  {
    "id": "IND21-Q27(a)",
    "year": 2021,
    "n": 27,
    "part": "a",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_q27.png",
    "w": 1644,
    "h": 1668,
    "criteria": "Draws and labels THREE forces — 1",
    "sample": "Three forces act on the sphere: its weight (mg, acting straight down), the tension in the string (acting along the string, towards the support), and the electrostatic force (qE, acting horizontally, in the direction of the field lines since the charge is positive)."
  },
  {
    "id": "IND21-Q27(b)",
    "year": 2021,
    "n": 27,
    "part": "b",
    "marks": 3,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_q27.png",
    "w": 1644,
    "h": 1668,
    "criteria": "Calculates the correct answer using components or a closed triangle of vectors — 3\nProvides TWO correct steps of the calculation — 2\nProvides ONE correct step of the calculation — 1",
    "sample": "Resolving forces on the sphere (in equilibrium), with the string at 30° to the vertical:\nT cos30° = mg, so T = (0.0050 × 9.8) / cos30°\nqE = T sin30°, so E = T sin30° / q = (0.0050 × 9.8 × tan30°) / (4 × 10^-4) ≈ 71 N/C"
  },
  {
    "id": "IND21-Q28(a)",
    "year": 2021,
    "n": 28,
    "part": "a",
    "marks": 3,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "IND21_q28.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Provides a detailed discussion based on the shape of the graphs, the definition of resistance, and the increase in temperature — 3\nRelates the graph's gradient to the resistance difference and to increasing temperature — 2\nIdentifies a difference in resistance between X and Y — 1",
    "sample": "Resistance is the ratio of voltage to current, equal to the gradient of a voltage-current graph. Resistor X gives a straight line through the origin, so its resistance is constant across the current range — it is an ohmic resistor. Resistor Y's graph has an increasing gradient, meaning its resistance increases as the current increases — it is non-ohmic. This is most likely because Y's temperature rises as more current flows through it, and resistance in a conductor typically increases with temperature."
  },
  {
    "id": "IND21-Q28(b)",
    "year": 2021,
    "n": 28,
    "part": "b",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "IND21_q28.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the plotting error — 1",
    "sample": "The dependent variable (current) has been plotted on the horizontal axis instead of the vertical axis — conventionally, the dependent variable is plotted on the y-axis."
  },
  {
    "id": "IND21-Q29(a)",
    "year": 2021,
    "n": 29,
    "part": "a",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Provides correct statement — 1",
    "sample": "To determine the relationship between the current flowing through a bundle of conductors (with a fixed number of conductors) and the magnetic field induced at a fixed distance from the bundle."
  },
  {
    "id": "IND21-Q29(b)",
    "year": 2021,
    "n": 29,
    "part": "b",
    "marks": 2,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Derives the appropriate relationship and states the hypothesis — 2\nDerives the appropriate relationship OR states the hypothesis — 1",
    "sample": "B = (mu_0 I) / (2 pi r). Since the number of conductors r (distance) and the constants are fixed in this experiment, B is directly proportional to I.\nHypothesis: the magnetic field induced at a fixed distance from a bundle of current-carrying conductors is directly proportional to the current in the conductors."
  },
  {
    "id": "IND21-Q29(c)",
    "year": 2021,
    "n": 29,
    "part": "c",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Explains why the hypothesis is supported — 1",
    "sample": "The current values in the table are in the ratio 1:2:3:4:5, and the corresponding magnetic field values are also in the ratio 1:2:3:4:5 — the hypothesis is supported."
  }
];
