// Preliminary Physics — Section II short-answer sub-questions
// Sourced from the 2021 NSW Independent Trial Exams, Physics Year 11 Examination,
// with official marking criteria and sample answers from that paper's marking
// guidelines. Drawing-only or graph-drawing sub-parts (17a, 17b, 18, 24) were
// dropped, matching the approach used for the Preliminary Biology quiz's own
// text-only exam bank.
const SA_QUESTIONS = [
  {
    "id": "IND21-Q16(a)",
    "year": 2021,
    "n": 16,
    "part": "a",
    "marks": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct answer — 1",
    "sample": "Distance travelled = total area between the graph and the time axis = (6 × 15)/2 + (10 × 25)/2 = 170 m"
  },
  {
    "id": "IND21-Q16(b)",
    "year": 2021,
    "n": 16,
    "part": "b",
    "marks": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct magnitude and direction — 2\nProvides correct magnitude — 1",
    "sample": "Displacement = 45 m south + 125 m north = 80 m north (adding the signed area under the graph before and after it crosses zero)"
  },
  {
    "id": "IND21-Q16(c)",
    "year": 2021,
    "n": 16,
    "part": "c",
    "marks": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_q16.png",
    "w": 1644,
    "h": 1971,
    "criteria": "Provides correct magnitude — 1",
    "sample": "Acceleration = gradient of the graph = 40/16 = 2.5 m/s² north"
  },
  {
    "id": "IND21-Q17(c)",
    "year": 2021,
    "n": 17,
    "part": "c",
    "marks": 2,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "IND21_q17.png",
    "w": 1644,
    "h": 1188,
    "criteria": "Calculates angle — 2\nCalculates acceleration only — 1",
    "sample": "Using s = ut + 1/2 a t^2 with u = 0: a = 2s/t^2 = 2(0.61)/(0.5)^2 = 4.9 m/s^2 (using the t = 0.5 s data point, distance 61 cm = 0.61 m)\nAcceleration down the slope = g sinθ, so 4.9 = 9.8 sinθ, sinθ = 0.5, θ = 30°"
  },
  {
    "id": "IND21-Q19(a)",
    "year": 2021,
    "n": 19,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q19.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates net force — 1",
    "sample": "From F = ma, net force on the box = 12 × 3.0 = 36 N in the direction of motion"
  },
  {
    "id": "IND21-Q19(b)",
    "year": 2021,
    "n": 19,
    "part": "b",
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q19.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates the coefficient of friction correctly — 3\nDetermines the frictional force correctly and calculates the coefficient of friction using the weight force only — 2\nDetermines the frictional force correctly — 1",
    "sample": "Horizontal component of tension in rope = 60 cos 40° = 46 N\nNet force = horizontal component of tension − frictional force, so frictional force = 46 − 36 = 10 N\nVertical component of tension = 60 sin 40° = 39 N\nNormal reaction force N = mg − vertical component of tension = (12 × 9.8) − 39 = 79 N\nKinetic coefficient of friction = friction force / N = 10 / 79 = 0.13"
  },
  {
    "id": "IND21-Q20(a)",
    "year": 2021,
    "n": 20,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Determines acceleration — 1",
    "sample": "At displacement 30 m East, force = 32 N East (read from the graph)\nAcceleration = F/m = 32/5.0 = 6.4 m/s² East"
  },
  {
    "id": "IND21-Q20(b)",
    "year": 2021,
    "n": 20,
    "part": "b",
    "marks": 2,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates work done correctly — 2\nCalculates the area under the graph with an error — 1",
    "sample": "Work done = area under the graph from 0 to 30 m = (25 × 40) + 0.5(40 + 32)(5) = 1000 + 180 = 1180 J"
  },
  {
    "id": "IND21-Q20(c)",
    "year": 2021,
    "n": 20,
    "part": "c",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_q20.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates velocity — 1",
    "sample": "By the work-energy theorem, kinetic energy gained = work done: 1/2 m v^2 = 1180, so v = sqrt(2 × 1180 / 5.0) = 21.7 m/s East"
  },
  {
    "id": "IND21-Q21",
    "year": 2021,
    "n": 21,
    "part": null,
    "marks": 3,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q21.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Evaluates BOTH statements about momentum correctly and identifies THREE mistakes about kinetic energy — 3\nEvaluates BOTH statements about momentum correctly and identifies ONE mistake about kinetic energy — 2\nEvaluates BOTH statements about momentum correctly — 1",
    "sample": "Both students are correct to use a vector diagram to compare momentum before and after the explosion, because momentum is a vector and is conserved in all interactions with no external force — the explosion here is an internal force within the system.\nHowever, both are incorrect about kinetic energy: it is a scalar, not a vector, so it cannot be added or compared using a vector diagram. The system's kinetic energy starts at zero and is clearly not zero afterwards, so kinetic energy is not conserved — Carol's conclusion about momentum is right, but Tom's claim that kinetic energy is also conserved is wrong, and neither student's vector-diagram method for energy is valid."
  },
  {
    "id": "IND21-Q22(a)",
    "year": 2021,
    "n": 22,
    "part": "a",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates magnitude of velocity — 1",
    "sample": "By conservation of momentum: (1000)(20) + 0 = (1000 + 800)v, so v = 20000/1800 = 11.1 m/s to the right"
  },
  {
    "id": "IND21-Q22(b)",
    "year": 2021,
    "n": 22,
    "part": "b",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates impulse — 1",
    "sample": "Momentum of car Y after collision = 800 × 11.1 = 8880 Ns to the right. Since car Y started at rest, its change in momentum (= impulse applied to it by car X) is also 8880 Ns to the right."
  },
  {
    "id": "IND21-Q22(c)",
    "year": 2021,
    "n": 22,
    "part": "c",
    "marks": 1,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_q22.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Calculates force — 1",
    "sample": "By Newton's Third Law, the impulse on car X is 8880 Ns to the left. Force on car X = impulse / time = 8880 / 0.10 = 88 800 N to the left"
  },
  {
    "id": "IND21-Q23(a)",
    "year": 2021,
    "n": 23,
    "part": "a",
    "marks": 1,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Provides correct answer — 1",
    "sample": "The natural (resonant) frequency of the spring is 70 × 10^3 Hz — the frequency at which the maximum amplitude of vibration (3.5 × 10^-4 cm) occurs in the table."
  },
  {
    "id": "IND21-Q23(b)",
    "year": 2021,
    "n": 23,
    "part": "b",
    "marks": 1,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Identifies ultrasound — 1",
    "sample": "The ultrasonic sound source drives the spring to oscillate."
  },
  {
    "id": "IND21-Q23(c)",
    "year": 2021,
    "n": 23,
    "part": "c",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_q23.png",
    "w": 1644,
    "h": 2173,
    "criteria": "Identifies increased amplitude and gives the reason — 2\nIdentifies increased amplitude only — 1",
    "sample": "If the intensity of the ultrasound (the driving force) were increased, the amplitude of the spring's oscillations would increase at every frequency, because more energy is being supplied to drive the resonance."
  },
  {
    "id": "IND21-Q25",
    "year": 2021,
    "n": 25,
    "part": null,
    "marks": 7,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "IND21_q25.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Compares in detail the motion of the particles, the energy transfer, and the appearance, with at least ONE example for each type of wave — 6–7\nProvides a comparison of THREE of: motion of particles, energy transfer, appearance, example for each — 4–5\nProvides a comparison of TWO of the above — 2–3\nProvides a comparison of ONE of the above — 1",
    "sample": "In a progressive wave, each particle of the medium undergoes identical vibrations, slightly out of step (out of phase) with its neighbours, and the disturbance itself moves steadily along the medium, transferring energy from one place to another. Its wavelength is the distance between two particles that are in phase, e.g. crest to crest.\nIn a standing wave, energy is not transferred along the medium — it is reflected back and forth between the boundaries of the system. Some points, called nodes, never vibrate at all, while points midway between adjacent nodes, called antinodes, vibrate with maximum amplitude; particles on opposite sides of a node vibrate in opposite phase. Its wavelength is twice the distance between two adjacent nodes.\nBoth transverse and longitudinal waves can be either progressive or standing.\nExamples of progressive waves include surface water waves and sound travelling through open air. Examples of standing waves include a vibrating violin string and the air column inside a wind instrument being played."
  },
  {
    "id": "IND21-Q26(a)",
    "year": 2021,
    "n": 26,
    "part": "a",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "IND21_q26.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the constant temperature and the continued energy input — 2\nIdentifies the constant temperature OR the continued energy input — 1",
    "sample": "While the ice is melting, its temperature stays constant at 0°C even though heat energy is still being supplied at a steady rate. This heat energy is being used to change the ice from the solid state to the liquid state, rather than to raise its temperature — this 'hidden' energy is the latent heat of fusion."
  },
  {
    "id": "IND21-Q26(b)",
    "year": 2021,
    "n": 26,
    "part": "b",
    "marks": 2,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "IND21_q26.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the change in structure of the particles in the solid and liquid states and the need to overcome intermolecular forces — 2\nIdentifies the change in structure OR the need to overcome forces — 1",
    "sample": "The energy supplied is absorbed by the particles of ice and used to overcome the intermolecular forces holding them in fixed positions within the solid lattice. This lets the particles break free of their fixed positions and move over one another, as they do in the liquid state."
  },
  {
    "id": "IND21-Q27(a)",
    "year": 2021,
    "n": 27,
    "part": "a",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_q27.png",
    "w": 1644,
    "h": 1668,
    "criteria": "Draws and labels THREE forces — 1",
    "sample": "Three forces act on the sphere: its weight (mg, acting straight down), the tension in the string (acting along the string, towards the support), and the electrostatic force (qE, acting horizontally, in the direction of the field lines since the charge is positive)."
  },
  {
    "id": "IND21-Q27(b)",
    "year": 2021,
    "n": 27,
    "part": "b",
    "marks": 3,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_q27.png",
    "w": 1644,
    "h": 1668,
    "criteria": "Calculates the correct answer using components or a closed triangle of vectors — 3\nProvides TWO correct steps of the calculation — 2\nProvides ONE correct step of the calculation — 1",
    "sample": "Resolving forces on the sphere (in equilibrium), with the string at 30° to the vertical:\nT cos30° = mg, so T = (0.0050 × 9.8) / cos30°\nqE = T sin30°, so E = T sin30° / q = (0.0050 × 9.8 × tan30°) / (4 × 10^-4) ≈ 71 N/C"
  },
  {
    "id": "IND21-Q28(a)",
    "year": 2021,
    "n": 28,
    "part": "a",
    "marks": 3,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "IND21_q28.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Provides a detailed discussion based on the shape of the graphs, the definition of resistance, and the increase in temperature — 3\nRelates the graph's gradient to the resistance difference and to increasing temperature — 2\nIdentifies a difference in resistance between X and Y — 1",
    "sample": "Resistance is the ratio of voltage to current, equal to the gradient of a voltage-current graph. Resistor X gives a straight line through the origin, so its resistance is constant across the current range — it is an ohmic resistor. Resistor Y's graph has an increasing gradient, meaning its resistance increases as the current increases — it is non-ohmic. This is most likely because Y's temperature rises as more current flows through it, and resistance in a conductor typically increases with temperature."
  },
  {
    "id": "IND21-Q28(b)",
    "year": 2021,
    "n": 28,
    "part": "b",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "IND21_q28.png",
    "w": 1644,
    "h": 2047,
    "criteria": "Identifies the plotting error — 1",
    "sample": "The dependent variable (current) has been plotted on the horizontal axis instead of the vertical axis — conventionally, the dependent variable is plotted on the y-axis."
  },
  {
    "id": "IND21-Q29(a)",
    "year": 2021,
    "n": 29,
    "part": "a",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Provides correct statement — 1",
    "sample": "To determine the relationship between the current flowing through a bundle of conductors (with a fixed number of conductors) and the magnetic field induced at a fixed distance from the bundle."
  },
  {
    "id": "IND21-Q29(b)",
    "year": 2021,
    "n": 29,
    "part": "b",
    "marks": 2,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Derives the appropriate relationship and states the hypothesis — 2\nDerives the appropriate relationship OR states the hypothesis — 1",
    "sample": "B = (mu_0 I) / (2 pi r). Since the number of conductors r (distance) and the constants are fixed in this experiment, B is directly proportional to I.\nHypothesis: the magnetic field induced at a fixed distance from a bundle of current-carrying conductors is directly proportional to the current in the conductors."
  },
  {
    "id": "IND21-Q29(c)",
    "year": 2021,
    "n": 29,
    "part": "c",
    "marks": 1,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_q29.png",
    "w": 1644,
    "h": 1617,
    "criteria": "Explains why the hypothesis is supported — 1",
    "sample": "The current values in the table are in the ratio 1:2:3:4:5, and the corresponding magnetic field values are also in the ratio 1:2:3:4:5 — the hypothesis is supported."
  }
];
